import { Job, Application, CandidateProfile, RecruiterProfile, User } from "../../types";

const INITIAL_USERS: User[] = [
  {
    id: "user-cand-1",
    name: "Alex Mercer",
    email: "alex.mercer@example.com",
    role: "candidate",
    createdAt: "2026-01-15T08:00:00Z",
  },
  {
    id: "user-cand-2",
    name: "Elena Rostova",
    email: "elena.r@example.com",
    role: "candidate",
    createdAt: "2026-02-01T10:30:00Z",
  },
  {
    id: "user-cand-3",
    name: "Marcus Chen",
    email: "marcus.chen@example.com",
    role: "candidate",
    createdAt: "2026-02-12T14:15:00Z",
  },
  {
    id: "user-rec-1",
    name: "Sarah Lin",
    email: "sarah.lin@acmecloud.io",
    role: "recruiter",
    companyName: "Acme Cloud Infrastructure",
    createdAt: "2025-11-20T09:00:00Z",
  },
  {
    id: "user-rec-2",
    name: "David Vance",
    email: "d.vance@vanguardtechnologies.com",
    role: "recruiter",
    companyName: "Vanguard Systems",
    createdAt: "2025-12-05T11:45:00Z",
  },
];

const INITIAL_JOBS: Job[] = [
  {
    id: "job-101",
    title: "Senior Full Stack Engineer",
    company: "Acme Cloud Infrastructure",
    location: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    experience: "4-6 Years",
    minSalary: 145000,
    maxSalary: 185000,
    department: "Engineering",
    description: `We are looking for a Senior Full Stack Engineer to lead architecture across our distributed telemetry platform. You will build high-throughput APIs, refine stateful frontend components, and collaborate with cloud architects to maintain 99.99% availability.

Responsibilities:
• Design, build, and maintain high-performance, fault-tolerant Node.js and Go microservices.
• Develop responsive, accessible web interfaces in React and TypeScript.
• Partner with product managers and site reliability engineers to scope roadmaps.
• Conduct code reviews and mentor mid-level engineering teammates.

Qualifications:
• 4+ years of professional full-stack development experience.
• Proficiency in TypeScript, React, and modern CSS frameworks.
• Deep familiarity with relational databases (PostgreSQL) and caching layers (Redis).
• Strong communication skills and empathy for developer tooling.`,
    applicationUrl: "https://acmecloud.io/careers/job-101",
    status: "Active",
    postedDate: "2026-03-28T10:00:00Z",
    recruiterId: "user-rec-1",
    applicantCount: 14,
  },
  {
    id: "job-102",
    title: "Lead Product Designer",
    company: "Acme Cloud Infrastructure",
    location: "San Francisco, CA (Remote)",
    employmentType: "Full Time",
    experience: "5+ Years",
    minSalary: 135000,
    maxSalary: 170000,
    department: "Design",
    description: `Acme Cloud is seeking a Lead Product Designer to own user experience across our core infrastructure management console.

Key Objectives:
• Translate complex infrastructure topologies into intuitive, uncluttered user flows.
• Oversee the evolution of our design token system in Figma and code sync.
• Run weekly candidate and customer feedback interviews to test prototype hypotheses.
• Champion accessibility (WCAG AA) across all product surfaces.

Requirements:
• 5+ years designing enterprise SaaS, cloud management tools, or developer platforms.
• Mastery of Figma, design systems, and rapid interactive prototyping.
• Solid grasp of frontend constraints (CSS Grid, flexbox, reactive states).`,
    applicationUrl: "https://acmecloud.io/careers/job-102",
    status: "Active",
    postedDate: "2026-03-30T14:30:00Z",
    recruiterId: "user-rec-1",
    applicantCount: 9,
  },
  {
    id: "job-103",
    title: "DevOps & Cloud Systems Engineer",
    company: "Vanguard Systems",
    location: "Austin, TX (On-Site)",
    employmentType: "Full Time",
    experience: "3-5 Years",
    minSalary: 130000,
    maxSalary: 160000,
    department: "Infrastructure",
    description: `Vanguard Systems is expanding our platform reliability squad. In this role, you will modernize our Kubernetes container clusters and automate continuous verification pipelines.

Key Responsibilities:
• Maintain multi-region Kubernetes deployments using Terraform and ArgoCD.
• Reduce deployment latency and enhance observability using Prometheus and Grafana.
• Participate in a respectful, blameless on-call rotation with predictable schedules.

Qualifications:
• Proven track record with AWS, GCP, or bare-metal Linux administration.
• Strong command of Bash, Python, or Go for operational automation.`,
    applicationUrl: "https://vanguardtechnologies.com/careers/103",
    status: "Active",
    postedDate: "2026-04-01T09:15:00Z",
    recruiterId: "user-rec-2",
    applicantCount: 6,
  },
  {
    id: "job-104",
    title: "Frontend Engineering Intern (Summer 2026)",
    company: "Vanguard Systems",
    location: "Remote (US)",
    employmentType: "Internship",
    experience: "0-1 Years",
    minSalary: 55000,
    maxSalary: 72000,
    department: "Engineering",
    description: `An intensive 12-week paid internship for aspiring frontend builders. You will work side-by-side with senior engineers on shipping real customer-facing features.

What you'll do:
• Build modular UI components using React, TypeScript, and Tailwind CSS.
• Write comprehensive unit and integration tests.
• Present your final capstone feature to company engineering leadership.

Who you are:
• Currently pursuing a Degree or Bootcamp certificate in CS or related field.
• Hands-on familiarity with JavaScript/TypeScript and web standards.`,
    applicationUrl: "https://vanguardtechnologies.com/careers/104",
    status: "Active",
    postedDate: "2026-04-02T11:00:00Z",
    recruiterId: "user-rec-2",
    applicantCount: 22,
  },
  {
    id: "job-105",
    title: "Technical Content & Documentation Specialist",
    company: "Acme Cloud Infrastructure",
    location: "Remote",
    employmentType: "Contract",
    experience: "2-4 Years",
    minSalary: 85000,
    maxSalary: 110000,
    department: "Documentation",
    description: `Help us craft clear, accurate, and developer-friendly documentation for our APIs and SDKs.

What you will do:
• Audit existing developer guides and write reproducible quickstarts.
• Collaborate with API architects to ensure docs reflect upcoming schema updates.
• Implement syntax-highlighted code samples in TypeScript, Python, and cURL.`,
    status: "Active",
    postedDate: "2026-03-25T16:00:00Z",
    recruiterId: "user-rec-1",
    applicantCount: 5,
  },
  {
    id: "job-106",
    title: "Data Operations Analyst",
    company: "Vanguard Systems",
    location: "New York, NY (Hybrid)",
    employmentType: "Full Time",
    experience: "2-4 Years",
    minSalary: 95000,
    maxSalary: 125000,
    department: "Data",
    description: `We are seeking an analytical thinker to organize pipeline metrics, build operational dashboards, and audit data hygiene across customer cohorts.`,
    status: "Active",
    postedDate: "2026-03-20T08:00:00Z",
    recruiterId: "user-rec-2",
    applicantCount: 11,
  },
  {
    id: "job-107",
    title: "Application Security Analyst",
    company: "Acme Cloud Infrastructure",
    location: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    experience: "3-6 Years",
    minSalary: 140000,
    maxSalary: 175000,
    department: "Security",
    description: `Lead vulnerability scans, dependency audits, and threat modeling for our client-facing services and containerized workloads.`,
    status: "Active",
    postedDate: "2026-03-18T13:45:00Z",
    recruiterId: "user-rec-1",
    applicantCount: 7,
  },
  {
    id: "job-108",
    title: "Product Support Specialist (Part-Time)",
    company: "Vanguard Systems",
    location: "Remote",
    employmentType: "Part Time",
    experience: "1-2 Years",
    minSalary: 38000,
    maxSalary: 48000,
    department: "Support",
    description: `Provide empathetic, knowledgeable tier-2 troubleshooting support to enterprise platform administrators on a 20 hours/week schedule.`,
    status: "Active",
    postedDate: "2026-03-15T10:10:00Z",
    recruiterId: "user-rec-2",
    applicantCount: 4,
  },
];

const INITIAL_APPLICATIONS: Application[] = [
  // Alex Mercer (Active Candidate user-cand-1) Applications
  {
    id: "app-201",
    jobId: "job-101",
    jobTitle: "Senior Full Stack Engineer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-1",
    applicantName: "Alex Mercer",
    applicantEmail: "alex.mercer@example.com",
    applicantPhone: "+1 (555) 234-5678",
    appliedDate: "2026-03-29T11:20:00Z",
    status: "Under Review",
    notes: "Applied with full portfolio, open-source repositories, and Docker telemetry demo.",
    matchScore: 96,
    matchedSkills: ["TypeScript", "React", "Node.js", "PostgreSQL", "Docker", "REST APIs"],
    missingSkills: ["Go"],
    interviewStage: "Technical Phone Screen",
    recruiterFeedback: "Strong architecture depth and clean GitHub code samples. Scheduled for system design review.",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-9182",
      syncedAt: "2026-03-29T11:25:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-101-ENG",
    },
  },
  {
    id: "app-203",
    jobId: "job-103",
    jobTitle: "DevOps & Cloud Systems Engineer",
    company: "Vanguard Systems",
    jobLocation: "Austin, TX (On-Site)",
    employmentType: "Full Time",
    applicantId: "user-cand-1",
    applicantName: "Alex Mercer",
    applicantEmail: "alex.mercer@example.com",
    applicantPhone: "+1 (555) 234-5678",
    appliedDate: "2026-04-02T13:40:00Z",
    status: "Shortlisted",
    notes: "Highlighted Kubernetes deployment automation and Linux systems background.",
    matchScore: 89,
    matchedSkills: ["Docker", "Linux", "Terraform", "Git"],
    missingSkills: ["Prometheus", "ArgoCD"],
    interviewStage: "Architecture Deep-Dive",
    recruiterFeedback: "Invited to on-site infrastructure simulation round.",
    atsSync: {
      status: "synced",
      atsProvider: "Lever",
      candidateAtsId: "LEV-OPP-4819",
      syncedAt: "2026-04-02T13:45:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-103-OPS",
    },
  },
  {
    id: "app-206",
    jobId: "eng-vlsi-rtl-hyd-101",
    jobTitle: "Senior RTL Design & ASIC Verification Engineer",
    company: "SiliconPulse Microelectronics",
    jobLocation: "Hyderabad, Telangana (Hitec City)",
    employmentType: "Full Time",
    applicantId: "user-cand-1",
    applicantName: "Alex Mercer",
    applicantEmail: "alex.mercer@example.com",
    applicantPhone: "+1 (555) 234-5678",
    appliedDate: "2026-04-04T09:15:00Z",
    status: "Applied",
    notes: "Applying for cross-functional embedded systems interface and telemetry tooling.",
    matchScore: 78,
    matchedSkills: ["C/C++", "Linux", "System Architecture", "Git"],
    missingSkills: ["SystemVerilog", "UVM"],
    interviewStage: "Initial Application Screening",
    atsSync: {
      status: "synced",
      atsProvider: "Workday",
      candidateAtsId: "WD-APPL-78192",
      syncedAt: "2026-04-04T09:18:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-VLSI-HYD",
    },
  },
  {
    id: "app-207",
    jobId: "gov-upsc-eng-2026-04",
    jobTitle: "UPSC Engineering Services Examination (ESE 2026)",
    company: "Union Public Service Commission (UPSC)",
    jobLocation: "New Delhi, Delhi (All India Service)",
    employmentType: "Full Time",
    applicantId: "user-cand-1",
    applicantName: "Alex Mercer",
    applicantEmail: "alex.mercer@example.com",
    applicantPhone: "+1 (555) 234-5678",
    appliedDate: "2026-04-01T08:00:00Z",
    status: "Applied",
    notes: "Official candidature logged via UPSC OTR registration ID 202684910.",
    matchScore: 84,
    matchedSkills: ["Engineering Fundamentals", "Public Administration", "Technical Management"],
    missingSkills: ["General Studies"],
    interviewStage: "Preliminary Examination Cadence",
  },
  {
    id: "app-208",
    jobId: "job-107",
    jobTitle: "Application Security Analyst",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-1",
    applicantName: "Alex Mercer",
    applicantEmail: "alex.mercer@example.com",
    applicantPhone: "+1 (555) 234-5678",
    appliedDate: "2026-03-24T14:30:00Z",
    status: "Selected",
    notes: "Demonstrated automated dependency scanning and container vulnerability isolation.",
    matchScore: 92,
    matchedSkills: ["Docker", "Linux", "PostgreSQL", "REST APIs", "Node.js"],
    missingSkills: ["Penetration Testing"],
    interviewStage: "Offer Extended",
    recruiterFeedback: "Formal offer package dispatched with comprehensive benefits and equity incentive.",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-8192",
      syncedAt: "2026-03-24T14:35:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-107-SEC",
    },
  },

  // Recruiter Sarah Lin's Jobs (job-101, job-102, job-105, job-107) Pipeline Applications
  {
    id: "app-202",
    jobId: "job-102",
    jobTitle: "Lead Product Designer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Remote)",
    employmentType: "Full Time",
    applicantId: "user-cand-2",
    applicantName: "Elena Rostova",
    applicantEmail: "elena.r@example.com",
    applicantPhone: "+1 (555) 987-6543",
    appliedDate: "2026-03-31T09:10:00Z",
    status: "Shortlisted",
    notes: "Invited to portfolio presentation round with enterprise cloud design samples.",
    matchScore: 95,
    matchedSkills: ["Figma", "Design Systems", "UI/UX", "Prototyping", "User Research"],
    missingSkills: ["CSS Grid"],
    interviewStage: "Design Portfolio Presentation",
    recruiterFeedback: "Outstanding design token architecture and enterprise console walkthrough.",
    atsSync: {
      status: "synced",
      atsProvider: "Lever",
      candidateAtsId: "LEV-OPP-3819",
      syncedAt: "2026-03-31T09:15:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-102-DES",
    },
  },
  {
    id: "app-205",
    jobId: "job-101",
    jobTitle: "Senior Full Stack Engineer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-2",
    applicantName: "Elena Rostova",
    applicantEmail: "elena.r@example.com",
    applicantPhone: "+1 (555) 987-6543",
    appliedDate: "2026-03-30T10:00:00Z",
    status: "Rejected",
    notes: "Design lead profile redirected to Lead Product Designer requisition.",
    matchScore: 68,
    matchedSkills: ["UI/UX", "React"],
    missingSkills: ["Go", "PostgreSQL", "Redis"],
    interviewStage: "Application Redirected",
    recruiterFeedback: "Candidate possesses phenomenal design leadership; redirected to Design opening.",
  },
  {
    id: "app-209",
    jobId: "job-101",
    jobTitle: "Senior Full Stack Engineer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-4",
    applicantName: "Devon Vance",
    applicantEmail: "devon.vance@techlead.dev",
    applicantPhone: "+1 (555) 345-6789",
    appliedDate: "2026-04-01T14:10:00Z",
    status: "Shortlisted",
    notes: "10+ years engineering experience, architected multi-region Go and TypeScript services.",
    matchScore: 98,
    matchedSkills: ["TypeScript", "React", "Node.js", "Go", "PostgreSQL", "Redis", "Docker"],
    missingSkills: [],
    interviewStage: "Executive Systems Panel",
    recruiterFeedback: "Top-tier distributed systems knowledge. Final panel scheduled.",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-9912",
      syncedAt: "2026-04-01T14:15:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-101-ENG",
    },
  },
  {
    id: "app-210",
    jobId: "job-101",
    jobTitle: "Senior Full Stack Engineer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-5",
    applicantName: "Aria Thorne",
    applicantEmail: "aria.thorne@designsystems.io",
    applicantPhone: "+1 (555) 456-7891",
    appliedDate: "2026-04-02T16:20:00Z",
    status: "Under Review",
    notes: "Frontend and micro-frontend specialist with React, Next.js, and Node experience.",
    matchScore: 91,
    matchedSkills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Node.js"],
    missingSkills: ["Go", "PostgreSQL"],
    interviewStage: "Technical Screen",
    recruiterFeedback: "Resume passed preliminary screening; reviewing frontend architectural portfolio.",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-9934",
      syncedAt: "2026-04-02T16:25:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-101-ENG",
    },
  },
  {
    id: "app-211",
    jobId: "job-101",
    jobTitle: "Senior Full Stack Engineer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-6",
    applicantName: "Kai Takahashi",
    applicantEmail: "kai.t@distributed.net",
    applicantPhone: "+1 (555) 567-8902",
    appliedDate: "2026-04-03T11:00:00Z",
    status: "Under Review",
    notes: "Deep backend reliability engineering and Redis caching expertise.",
    matchScore: 88,
    matchedSkills: ["Node.js", "Go", "PostgreSQL", "Redis", "Docker", "REST APIs"],
    missingSkills: ["React"],
    interviewStage: "Resume Review",
    atsSync: {
      status: "pending",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-9941",
      syncedAt: "2026-04-03T11:05:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-101-ENG",
    },
  },
  {
    id: "app-212",
    jobId: "job-101",
    jobTitle: "Senior Full Stack Engineer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-7",
    applicantName: "Maya Patel",
    applicantEmail: "m.patel@datascience.org",
    applicantPhone: "+1 (555) 678-9013",
    appliedDate: "2026-04-03T17:30:00Z",
    status: "Applied",
    notes: "Full-stack engineer with analytics platform background.",
    matchScore: 86,
    matchedSkills: ["TypeScript", "Python", "PostgreSQL", "React", "Docker"],
    missingSkills: ["Go", "Redis"],
    interviewStage: "Application Received",
  },
  {
    id: "app-213",
    jobId: "job-102",
    jobTitle: "Lead Product Designer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Remote)",
    employmentType: "Full Time",
    applicantId: "user-cand-8",
    applicantName: "Zane Holloway",
    applicantEmail: "zane.h@openprotocol.com",
    applicantPhone: "+1 (555) 789-0124",
    appliedDate: "2026-04-01T10:45:00Z",
    status: "Under Review",
    notes: "Senior UI/UX designer with 6 years experience in SaaS dashboard typography and tokens.",
    matchScore: 94,
    matchedSkills: ["Figma", "UI/UX", "Design Systems", "Prototyping"],
    missingSkills: ["WCAG AA"],
    interviewStage: "Portfolio Evaluation",
    atsSync: {
      status: "synced",
      atsProvider: "Lever",
      candidateAtsId: "LEV-OPP-3912",
      syncedAt: "2026-04-01T10:50:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-102-DES",
    },
  },
  {
    id: "app-214",
    jobId: "job-105",
    jobTitle: "Technical Content & Documentation Specialist",
    company: "Acme Cloud Infrastructure",
    jobLocation: "Remote",
    employmentType: "Contract",
    applicantId: "user-cand-9",
    applicantName: "Priya Sharma",
    applicantEmail: "priya.sharma@techdocs.io",
    applicantPhone: "+1 (555) 890-1235",
    appliedDate: "2026-03-27T12:00:00Z",
    status: "Selected",
    notes: "Author of popular TypeScript open-source developer documentation portals.",
    matchScore: 97,
    matchedSkills: ["Technical Writing", "TypeScript", "Python", "API Documentation", "Git"],
    missingSkills: [],
    interviewStage: "Offer Extended",
    recruiterFeedback: "Exceptional writing sample provided. Offer approved by VP of Product.",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-7810",
      syncedAt: "2026-03-27T12:05:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-105-DOC",
    },
  },
  {
    id: "app-215",
    jobId: "job-105",
    jobTitle: "Technical Content & Documentation Specialist",
    company: "Acme Cloud Infrastructure",
    jobLocation: "Remote",
    employmentType: "Contract",
    applicantId: "user-cand-10",
    applicantName: "Rahul Verma",
    applicantEmail: "r.verma@devwriters.net",
    applicantPhone: "+1 (555) 901-2346",
    appliedDate: "2026-03-28T15:20:00Z",
    status: "Rejected",
    notes: "Strong generalist background, but position required active TypeScript and API documentation portfolio.",
    matchScore: 72,
    matchedSkills: ["Technical Writing", "Git"],
    missingSkills: ["TypeScript", "API Documentation"],
    interviewStage: "Application Reviewed",
  },

  // Vanguard Systems Requisitions Pipeline (job-103, job-104, job-106, job-108)
  {
    id: "app-204",
    jobId: "job-104",
    jobTitle: "Frontend Engineering Intern (Summer 2026)",
    company: "Vanguard Systems",
    jobLocation: "Remote (US)",
    employmentType: "Internship",
    applicantId: "user-cand-3",
    applicantName: "Marcus Chen",
    applicantEmail: "marcus.chen@example.com",
    applicantPhone: "+1 (555) 456-7890",
    appliedDate: "2026-04-03T15:00:00Z",
    status: "Selected",
    notes: "Offer extended for Summer 2026 intern cohort.",
    matchScore: 94,
    matchedSkills: ["React", "TypeScript", "Tailwind CSS", "Git"],
    missingSkills: ["Docker"],
    interviewStage: "Offer Accepted",
    recruiterFeedback: "Ace coding challenge score. Excited to welcome Marcus to the team.",
    atsSync: {
      status: "synced",
      atsProvider: "Workday",
      candidateAtsId: "WD-APPL-90214",
      syncedAt: "2026-04-03T15:05:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-104-INT",
    },
  },
  {
    id: "app-216",
    jobId: "job-104",
    jobTitle: "Frontend Engineering Intern (Summer 2026)",
    company: "Vanguard Systems",
    jobLocation: "Remote (US)",
    employmentType: "Internship",
    applicantId: "user-cand-11",
    applicantName: "Sunita Reddy",
    applicantEmail: "sunita.reddy@campus.edu",
    applicantPhone: "+1 (555) 012-3457",
    appliedDate: "2026-04-02T18:00:00Z",
    status: "Shortlisted",
    notes: "Sophomore CS student with full-stack React and UI hackathon awards.",
    matchScore: 91,
    matchedSkills: ["React", "TypeScript", "Tailwind CSS", "Git"],
    missingSkills: ["Testing"],
    interviewStage: "Pair Programming Interview",
    atsSync: {
      status: "synced",
      atsProvider: "Workday",
      candidateAtsId: "WD-APPL-90218",
      syncedAt: "2026-04-02T18:05:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-104-INT",
    },
  },
  {
    id: "app-217",
    jobId: "job-104",
    jobTitle: "Frontend Engineering Intern (Summer 2026)",
    company: "Vanguard Systems",
    jobLocation: "Remote (US)",
    employmentType: "Internship",
    applicantId: "user-cand-12",
    applicantName: "Karthik Nair",
    applicantEmail: "karthik.n@university.edu",
    applicantPhone: "+1 (555) 123-4568",
    appliedDate: "2026-04-03T10:10:00Z",
    status: "Under Review",
    notes: "Junior at BITS Pilani with open-source contributions to component libraries.",
    matchScore: 89,
    matchedSkills: ["React", "TypeScript", "HTML/CSS", "Git"],
    missingSkills: ["Tailwind CSS"],
    interviewStage: "Technical Screen",
  },
  {
    id: "app-218",
    jobId: "job-103",
    jobTitle: "DevOps & Cloud Systems Engineer",
    company: "Vanguard Systems",
    jobLocation: "Austin, TX (On-Site)",
    employmentType: "Full Time",
    applicantId: "user-cand-6",
    applicantName: "Kai Takahashi",
    applicantEmail: "kai.t@distributed.net",
    applicantPhone: "+1 (555) 567-8902",
    appliedDate: "2026-04-02T11:45:00Z",
    status: "Under Review",
    notes: "5 years managing AWS multi-region Kubernetes clusters with Terraform.",
    matchScore: 96,
    matchedSkills: ["Kubernetes", "Docker", "Terraform", "Linux", "AWS", "Prometheus"],
    missingSkills: ["Go"],
    interviewStage: "Infrastructure Systems Interview",
    atsSync: {
      status: "synced",
      atsProvider: "Lever",
      candidateAtsId: "LEV-OPP-4822",
      syncedAt: "2026-04-02T11:50:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-103-OPS",
    },
  },
  {
    id: "app-219",
    jobId: "job-106",
    jobTitle: "Data Operations Analyst",
    company: "Vanguard Systems",
    jobLocation: "New York, NY (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-7",
    applicantName: "Maya Patel",
    applicantEmail: "m.patel@datascience.org",
    applicantPhone: "+1 (555) 678-9013",
    appliedDate: "2026-03-25T14:00:00Z",
    status: "Shortlisted",
    notes: "Strong SQL data warehousing and operational telemetry background.",
    matchScore: 93,
    matchedSkills: ["SQL", "PostgreSQL", "Data Analytics", "Python", "Tableau"],
    missingSkills: ["Airflow"],
    interviewStage: "Data Take-Home Exercise",
    recruiterFeedback: "Delivered comprehensive cohort churn model. Moving to team panel.",
    atsSync: {
      status: "synced",
      atsProvider: "Workday",
      candidateAtsId: "WD-APPL-81920",
      syncedAt: "2026-03-25T14:05:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-106-DAT",
    },
  },
  {
    id: "app-220",
    jobId: "job-106",
    jobTitle: "Data Operations Analyst",
    company: "Vanguard Systems",
    jobLocation: "New York, NY (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-13",
    applicantName: "Jordan Hayes",
    applicantEmail: "jordan.hayes@metrics.io",
    applicantPhone: "+1 (555) 234-5679",
    appliedDate: "2026-03-26T16:40:00Z",
    status: "Applied",
    notes: "3 years experience optimizing analytics pipelines and automated reporting.",
    matchScore: 88,
    matchedSkills: ["SQL", "Python", "PostgreSQL", "Excel"],
    missingSkills: ["Tableau"],
    interviewStage: "Application Screening",
  },
  {
    id: "app-221",
    jobId: "ncs-ap-it-2026-01",
    jobTitle: "State IT Consultant & Full Stack Architect",
    company: "National Career Service / AP State Govt",
    jobLocation: "Vijayawada, Andhra Pradesh",
    employmentType: "Full Time",
    applicantId: "user-cand-1",
    applicantName: "Alex Mercer",
    applicantEmail: "alex.mercer@example.com",
    applicantPhone: "+1 (555) 234-5678",
    appliedDate: "2026-04-03T08:30:00Z",
    status: "Under Review",
    notes: "Applied via National Career Service portal with AP civil informatics credentials.",
    matchScore: 93,
    matchedSkills: ["TypeScript", "React", "PostgreSQL", "Node.js", "System Architecture"],
    missingSkills: ["Telugu Official Gazette Documentation"],
    interviewStage: "Technical Competency Verification",
    atsSync: {
      status: "synced",
      atsProvider: "Workday",
      candidateAtsId: "WD-APPL-99201",
      syncedAt: "2026-04-03T08:35:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-NCS-AP-01",
    },
  },
  {
    id: "app-222",
    jobId: "ncs-ts-vlsi-2026-02",
    jobTitle: "Semiconductor & VLSI Embedded Systems Lead",
    company: "TS Electronic Hardware Directorate",
    jobLocation: "Hyderabad, Telangana (Hitec City)",
    employmentType: "Full Time",
    applicantId: "user-cand-1",
    applicantName: "Alex Mercer",
    applicantEmail: "alex.mercer@example.com",
    applicantPhone: "+1 (555) 234-5678",
    appliedDate: "2026-04-02T10:15:00Z",
    status: "Shortlisted",
    notes: "Demonstrated low-latency telemetry bus and Linux kernel driver integration experience.",
    matchScore: 88,
    matchedSkills: ["Embedded C", "Linux", "System Architecture", "Git"],
    missingSkills: ["VHDL"],
    interviewStage: "Technical Panel & Hardware Lab Review",
    recruiterFeedback: "Candidate displays strong system-level driver acumen. Panel scheduled.",
    atsSync: {
      status: "synced",
      atsProvider: "Lever",
      candidateAtsId: "LEV-OPP-9102",
      syncedAt: "2026-04-02T10:20:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-TS-VLSI-02",
    },
  },
  {
    id: "app-223",
    jobId: "gov-ssc-cgl-2026-02",
    jobTitle: "SSC CGL Group B Inspector & Technical Auditor",
    company: "Staff Selection Commission (SSC)",
    jobLocation: "New Delhi, Delhi",
    employmentType: "Full Time",
    applicantId: "user-cand-1",
    applicantName: "Alex Mercer",
    applicantEmail: "alex.mercer@example.com",
    applicantPhone: "+1 (555) 234-5678",
    appliedDate: "2026-04-01T12:00:00Z",
    status: "Applied",
    notes: "Direct application logged with authenticated roll code SSC-CGL-2026-8819.",
    matchScore: 82,
    matchedSkills: ["Public Administration", "Technical Management", "Quantitative Aptitude"],
    missingSkills: ["General Awareness Tier 2"],
    interviewStage: "Written Preliminary Examination",
  },
  {
    id: "app-224",
    jobId: "rem-401",
    jobTitle: "Principal Distributed Systems Engineer",
    company: "Remotive Network Global",
    jobLocation: "Remote (Worldwide)",
    employmentType: "Full Time",
    applicantId: "user-cand-1",
    applicantName: "Alex Mercer",
    applicantEmail: "alex.mercer@example.com",
    applicantPhone: "+1 (555) 234-5678",
    appliedDate: "2026-03-25T11:00:00Z",
    status: "Selected",
    notes: "Accepted offer for global high-throughput protocol infrastructure.",
    matchScore: 97,
    matchedSkills: ["TypeScript", "Node.js", "Docker", "PostgreSQL", "Kubernetes", "Redis"],
    missingSkills: [],
    interviewStage: "Offer Accepted & Onboarding Initiated",
    recruiterFeedback: "Phenomenal performance in distributed consensus exercise. Welcome aboard!",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-9988",
      syncedAt: "2026-03-25T11:05:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-REM-401",
    },
  },
  {
    id: "app-225",
    jobId: "job-101",
    jobTitle: "Senior Full Stack Engineer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-14",
    applicantName: "Vikram Joshi",
    applicantEmail: "vikram.joshi@distribsys.io",
    applicantPhone: "+1 (555) 345-6780",
    appliedDate: "2026-04-04T12:15:00Z",
    status: "Shortlisted",
    notes: "6 years experience building TypeScript, Go, and PostgreSQL distributed systems at scale.",
    matchScore: 95,
    matchedSkills: ["TypeScript", "React", "Node.js", "Go", "PostgreSQL", "Docker"],
    missingSkills: ["Redis"],
    interviewStage: "Architecture Design Panel",
    recruiterFeedback: "Demonstrated clear understanding of write-heavy caching patterns.",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-9952",
      syncedAt: "2026-04-04T12:20:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-101-ENG",
    },
  },
  {
    id: "app-226",
    jobId: "job-101",
    jobTitle: "Senior Full Stack Engineer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-15",
    applicantName: "Ananya Sen",
    applicantEmail: "ananya.sen@devplatform.org",
    applicantPhone: "+1 (555) 456-7892",
    appliedDate: "2026-04-04T14:45:00Z",
    status: "Under Review",
    notes: "Full-stack engineer with React frontend performance tuning and GraphQL federation expertise.",
    matchScore: 92,
    matchedSkills: ["React", "TypeScript", "Node.js", "GraphQL", "Tailwind CSS"],
    missingSkills: ["Go", "PostgreSQL"],
    interviewStage: "Technical Resume Review",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-9960",
      syncedAt: "2026-04-04T14:50:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-101-ENG",
    },
  },
  {
    id: "app-227",
    jobId: "job-102",
    jobTitle: "Lead Product Designer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Remote)",
    employmentType: "Full Time",
    applicantId: "user-cand-16",
    applicantName: "Rohan Gupta",
    applicantEmail: "rohan.g@designflows.com",
    applicantPhone: "+1 (555) 567-8904",
    appliedDate: "2026-04-03T16:20:00Z",
    status: "Under Review",
    notes: "Specialized in complex cloud developer workflows and multi-theme design systems.",
    matchScore: 90,
    matchedSkills: ["Figma", "UI/UX", "Design Systems", "Prototyping"],
    missingSkills: ["Accessibility Audits"],
    interviewStage: "Portfolio Initial Screen",
    atsSync: {
      status: "synced",
      atsProvider: "Lever",
      candidateAtsId: "LEV-OPP-3940",
      syncedAt: "2026-04-03T16:25:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-102-DES",
    },
  },
  {
    id: "app-228",
    jobId: "job-102",
    jobTitle: "Lead Product Designer",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Remote)",
    employmentType: "Full Time",
    applicantId: "user-cand-17",
    applicantName: "Sneha Reddy",
    applicantEmail: "sneha.reddy@interaction.io",
    applicantPhone: "+1 (555) 678-9015",
    appliedDate: "2026-04-02T11:10:00Z",
    status: "Shortlisted",
    notes: "8 years enterprise UX experience; previously led design tokens at SaaS unicorn.",
    matchScore: 97,
    matchedSkills: ["Figma", "Design Systems", "UI/UX", "User Research", "WCAG AA"],
    missingSkills: [],
    interviewStage: "Executive Design Presentation",
    recruiterFeedback: "Stunning portfolio with clear quantitative metrics on developer productivity gains.",
    atsSync: {
      status: "synced",
      atsProvider: "Lever",
      candidateAtsId: "LEV-OPP-3945",
      syncedAt: "2026-04-02T11:15:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-102-DES",
    },
  },
  {
    id: "app-229",
    jobId: "job-107",
    jobTitle: "Application Security Analyst",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-18",
    applicantName: "Farhan Akhtar",
    applicantEmail: "farhan.a@cyberdef.org",
    applicantPhone: "+1 (555) 789-0126",
    appliedDate: "2026-04-04T09:00:00Z",
    status: "Applied",
    notes: "Certified ethical hacker (CEH) with container vulnerability auditing and SOC2 compliance focus.",
    matchScore: 93,
    matchedSkills: ["Penetration Testing", "Docker", "Linux", "REST APIs"],
    missingSkills: ["PostgreSQL"],
    interviewStage: "Application Ingested",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-8210",
      syncedAt: "2026-04-04T09:05:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-107-SEC",
    },
  },
  {
    id: "app-230",
    jobId: "job-107",
    jobTitle: "Application Security Analyst",
    company: "Acme Cloud Infrastructure",
    jobLocation: "San Francisco, CA (Hybrid)",
    employmentType: "Full Time",
    applicantId: "user-cand-19",
    applicantName: "Chloe Zhao",
    applicantEmail: "chloe.zhao@appsec.net",
    applicantPhone: "+1 (555) 890-1237",
    appliedDate: "2026-04-01T15:30:00Z",
    status: "Shortlisted",
    notes: "5 years application penetration testing and threat modeling for Kubernetes deployments.",
    matchScore: 96,
    matchedSkills: ["Penetration Testing", "Docker", "Linux", "PostgreSQL", "Node.js", "Python"],
    missingSkills: [],
    interviewStage: "Hands-on Vulnerability Lab",
    recruiterFeedback: "Found all injected vulnerabilities in our staging sandbox under 20 minutes.",
    atsSync: {
      status: "synced",
      atsProvider: "Greenhouse",
      candidateAtsId: "GH-CAND-8218",
      syncedAt: "2026-04-01T15:35:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-107-SEC",
    },
  },
  {
    id: "app-231",
    jobId: "job-103",
    jobTitle: "DevOps & Cloud Systems Engineer",
    company: "Vanguard Systems",
    jobLocation: "Austin, TX (On-Site)",
    employmentType: "Full Time",
    applicantId: "user-cand-20",
    applicantName: "Samuel O'Connor",
    applicantEmail: "sam.oconnor@infraops.com",
    applicantPhone: "+1 (555) 901-2348",
    appliedDate: "2026-04-03T13:10:00Z",
    status: "Shortlisted",
    notes: "AWS Certified Solutions Architect with deep Terraform, Helm, and Prometheus experience.",
    matchScore: 95,
    matchedSkills: ["Kubernetes", "Docker", "AWS", "Terraform", "Prometheus", "Linux"],
    missingSkills: [],
    interviewStage: "On-site Cluster Reliability Simulation",
    recruiterFeedback: "High level of operational composure and infrastructure hygiene.",
    atsSync: {
      status: "synced",
      atsProvider: "Lever",
      candidateAtsId: "LEV-OPP-4830",
      syncedAt: "2026-04-03T13:15:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-103-OPS",
    },
  },
  {
    id: "app-232",
    jobId: "job-103",
    jobTitle: "DevOps & Cloud Systems Engineer",
    company: "Vanguard Systems",
    jobLocation: "Austin, TX (On-Site)",
    employmentType: "Full Time",
    applicantId: "user-cand-21",
    applicantName: "Neha Kapoor",
    applicantEmail: "neha.kapoor@cloudscale.io",
    applicantPhone: "+1 (555) 012-3459",
    appliedDate: "2026-03-28T10:00:00Z",
    status: "Selected",
    notes: "Accepted formal offer as Senior SRE and Infrastructure Architect.",
    matchScore: 98,
    matchedSkills: ["Kubernetes", "AWS", "Terraform", "Linux", "Docker", "Python", "Prometheus"],
    missingSkills: [],
    interviewStage: "Offer Accepted",
    recruiterFeedback: "Exceptional candidate with stellar references. Starting May 1st.",
    atsSync: {
      status: "synced",
      atsProvider: "Workday",
      candidateAtsId: "WD-APPL-78199",
      syncedAt: "2026-03-28T10:05:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-103-OPS",
    },
  },
  {
    id: "app-233",
    jobId: "job-108",
    jobTitle: "Product Support Specialist (Part-Time)",
    company: "Vanguard Systems",
    jobLocation: "Remote",
    employmentType: "Part Time",
    applicantId: "user-cand-22",
    applicantName: "Tara Washington",
    applicantEmail: "tara.w@customersuccess.io",
    applicantPhone: "+1 (555) 123-4560",
    appliedDate: "2026-03-29T14:20:00Z",
    status: "Selected",
    notes: "Tier-2 enterprise support lead with SQL and API debugging proficiency.",
    matchScore: 94,
    matchedSkills: ["Customer Support", "SQL", "REST APIs", "Troubleshooting"],
    missingSkills: [],
    interviewStage: "Offer Extended & Signed",
    recruiterFeedback: "Fantastic customer empathy and clear technical explanations.",
    atsSync: {
      status: "synced",
      atsProvider: "Workday",
      candidateAtsId: "WD-APPL-88210",
      syncedAt: "2026-03-29T14:25:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-108-SUP",
    },
  },
  {
    id: "app-234",
    jobId: "job-108",
    jobTitle: "Product Support Specialist (Part-Time)",
    company: "Vanguard Systems",
    jobLocation: "Remote",
    employmentType: "Part Time",
    applicantId: "user-cand-23",
    applicantName: "Carlos Mendez",
    applicantEmail: "carlos.m@supportdesk.net",
    applicantPhone: "+1 (555) 234-5671",
    appliedDate: "2026-04-01T11:40:00Z",
    status: "Shortlisted",
    notes: "Experienced with Zendesk, Jira Service Management, and REST API logging.",
    matchScore: 91,
    matchedSkills: ["Customer Support", "Troubleshooting", "REST APIs"],
    missingSkills: ["SQL"],
    interviewStage: "Simulated Customer Interaction",
    atsSync: {
      status: "synced",
      atsProvider: "Workday",
      candidateAtsId: "WD-APPL-88215",
      syncedAt: "2026-04-01T11:45:00Z",
      webhookDelivered: true,
      atsRequisitionCode: "REQ-108-SUP",
    },
  },
];

const INITIAL_CANDIDATE_PROFILES: Record<string, CandidateProfile> = {
  "user-cand-1": {
    id: "cand-prof-1",
    userId: "user-cand-1",
    name: "Alex Mercer",
    email: "alex.mercer@example.com",
    phone: "+1 (555) 234-5678",
    location: "San Francisco, CA",
    bio: "Senior software engineer with 5 years building high-reliability web applications, microservices, and design systems.",
    experience: "5 years in Full Stack Engineering (TypeScript, Node.js, React, PostgreSQL).",
    education: "B.S. in Computer Science, UC Berkeley",
    skills: ["TypeScript", "React", "Node.js", "PostgreSQL", "Tailwind CSS", "Docker"],
  },
};

const INITIAL_RECRUITER_PROFILES: Record<string, RecruiterProfile> = {
  "user-rec-1": {
    id: "rec-prof-1",
    userId: "user-rec-1",
    name: "Sarah Lin",
    email: "sarah.lin@acmecloud.io",
    companyName: "Acme Cloud Infrastructure",
    companyDescription: "Next-generation distributed telemetry and infrastructure platform for modern engineering teams.",
    companyLocation: "San Francisco, CA",
    website: "https://acmecloud.io",
    companySize: "250-500 employees",
  },
};

const STORAGE_KEYS = {
  USERS: "jobtrust_users_v1",
  JOBS: "jobtrust_jobs_v1",
  APPLICATIONS: "jobtrust_applications_v1",
  CANDIDATE_PROFILES: "jobtrust_cand_profiles_v1",
  RECRUITER_PROFILES: "jobtrust_rec_profiles_v1",
  CURRENT_USER: "jobtrust_current_user_v1",
  AUTH_TOKEN: "jobtrust_auth_token_v1",
};

function getStorage<T>(key: string, fallback: T): T {
  try {
    const raw = localStorage.getItem(key);
    if (!raw) return fallback;
    return JSON.parse(raw);
  } catch {
    return fallback;
  }
}

function setStorage<T>(key: string, data: T): void {
  try {
    localStorage.setItem(key, JSON.stringify(data));
  } catch (e) {
    console.error("Storage error:", e);
  }
}

export const MockStore = {
  init() {
    if (!localStorage.getItem(STORAGE_KEYS.USERS)) {
      setStorage(STORAGE_KEYS.USERS, INITIAL_USERS);
    }
    if (!localStorage.getItem(STORAGE_KEYS.JOBS)) {
      setStorage(STORAGE_KEYS.JOBS, INITIAL_JOBS);
    }
    if (!localStorage.getItem(STORAGE_KEYS.APPLICATIONS)) {
      setStorage(STORAGE_KEYS.APPLICATIONS, INITIAL_APPLICATIONS);
    }
    if (!localStorage.getItem(STORAGE_KEYS.CANDIDATE_PROFILES)) {
      setStorage(STORAGE_KEYS.CANDIDATE_PROFILES, INITIAL_CANDIDATE_PROFILES);
    }
    if (!localStorage.getItem(STORAGE_KEYS.RECRUITER_PROFILES)) {
      setStorage(STORAGE_KEYS.RECRUITER_PROFILES, INITIAL_RECRUITER_PROFILES);
    }
    // Default to candidate Alex Mercer if no current session
    if (!localStorage.getItem(STORAGE_KEYS.CURRENT_USER)) {
      setStorage(STORAGE_KEYS.CURRENT_USER, INITIAL_USERS[0]);
      setStorage(STORAGE_KEYS.AUTH_TOKEN, "demo-jwt-alex-mercer");
    }
  },

  getUsers(): User[] {
    return getStorage<User[]>(STORAGE_KEYS.USERS, INITIAL_USERS);
  },

  saveUsers(users: User[]) {
    setStorage(STORAGE_KEYS.USERS, users);
  },

  getCurrentUser(): User | null {
    return getStorage<User | null>(STORAGE_KEYS.CURRENT_USER, null);
  },

  setCurrentUser(user: User | null, token?: string) {
    if (user) {
      setStorage(STORAGE_KEYS.CURRENT_USER, user);
      if (token) setStorage(STORAGE_KEYS.AUTH_TOKEN, token);
    } else {
      localStorage.removeItem(STORAGE_KEYS.CURRENT_USER);
      localStorage.removeItem(STORAGE_KEYS.AUTH_TOKEN);
    }
  },

  getAuthToken(): string | null {
    return localStorage.getItem(STORAGE_KEYS.AUTH_TOKEN);
  },

  getJobs(): Job[] {
    return getStorage<Job[]>(STORAGE_KEYS.JOBS, INITIAL_JOBS);
  },

  saveJobs(jobs: Job[]) {
    setStorage(STORAGE_KEYS.JOBS, jobs);
  },

  getApplications(): Application[] {
    return getStorage<Application[]>(STORAGE_KEYS.APPLICATIONS, INITIAL_APPLICATIONS);
  },

  saveApplications(apps: Application[]) {
    setStorage(STORAGE_KEYS.APPLICATIONS, apps);
  },

  getCandidateProfiles(): Record<string, CandidateProfile> {
    return getStorage(STORAGE_KEYS.CANDIDATE_PROFILES, INITIAL_CANDIDATE_PROFILES);
  },

  saveCandidateProfiles(data: Record<string, CandidateProfile>) {
    setStorage(STORAGE_KEYS.CANDIDATE_PROFILES, data);
  },

  getRecruiterProfiles(): Record<string, RecruiterProfile> {
    return getStorage(STORAGE_KEYS.RECRUITER_PROFILES, INITIAL_RECRUITER_PROFILES);
  },

  saveRecruiterProfiles(data: Record<string, RecruiterProfile>) {
    setStorage(STORAGE_KEYS.RECRUITER_PROFILES, data);
  },

  resetDefaults() {
    localStorage.removeItem(STORAGE_KEYS.USERS);
    localStorage.removeItem(STORAGE_KEYS.JOBS);
    localStorage.removeItem(STORAGE_KEYS.APPLICATIONS);
    localStorage.removeItem(STORAGE_KEYS.CANDIDATE_PROFILES);
    localStorage.removeItem(STORAGE_KEYS.RECRUITER_PROFILES);
    localStorage.removeItem(STORAGE_KEYS.CURRENT_USER);
    localStorage.removeItem(STORAGE_KEYS.AUTH_TOKEN);
    this.init();
  },
};
